sudo: required
services:
  - docker

before_install:
  - docker build -t mk13/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mk13/multi-client-test npm test -- --coverage

after_success:
  - docker build -t mk13/multi-client ./client
  - docker build -t mk13/multi-nginx ./nginx
  - docker build -t mk13/multi-server ./server
  - docker build -t mk13/multi-worker ./worker
  # zaloguj sie do docker-cli na swoje konto dockerowe
  # zmienne logowania ustawiÄ‡ w travis-cli more options > settings > environment variables DOCKER_ID i DOCKER_PASSWORD
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # A teraz zabierz te obrazy dockerowe na hub.docker.com
  - docker push mk13/multi-client
  - docker push mk13/multi-nginx
  - docker push mk13/multi-server
  - docker push mk13/multi-worker